\c gungeon_dev


INSERT INTO weapons (name, notes, quote, quality, type, class, img) VALUES
('Casey', 'Charged swings reflect nearby bullets. Does not crack secret walls. Increases curse by 2.', 'Batting .50', 'D', 'Charged', 'SILLY', 'https://lh3.googleusercontent.com/61Ic4fKkRJEumi3v0yqQjZ06HThWHv3wv8okWYncRH3h9dYrbRmHKqIm-rLMPJpEcDZ9MknZkmSPNVnRnrUoxkE1ffPoEvOBmtuX-4oIWQ'),
('Microtransaction Gun', 'Shoots various figurines, books, and gems at the cost of 1 coin per shot.', 'Pay to Win', 'A', 'Semiautomatic', 'PISTOL', 'https://lh3.googleusercontent.com/L0pEVjY0g8ymUwT4SVExyvmYh-fnjkaGUXsMSo6Ez-tc8CdHGTSeEtD8OxJUBd4Ks9m6Ux2nIp2ZFfpzM1q05AYkENAxagkx8xbi_MqeOw'),
('Shock Rifle', 'Fires a zap of electricity.', 'Zap', 'B', 'Semiautomatic', 'RIFLE', 'https://lh3.googleusercontent.com/aD7XFTFNIQlBLAEyKMXgNUVMDwgGINDYcvYPhnpHkA41kYwkSQR9jsd0eO3V65IcrdyWSkZirNDRDqsvk9_bWziyZYn2U0_cYqTpfEGqAg'),
('Shell', 'Fires three shotguns, each of which fires three bullets upon hitting something.', 'Fires Shotguns', 'B', 'Semiautomatic', 'SHOTGUN', 'https://lh3.googleusercontent.com/T3YNxExA25mxNGbHSOZEyEF5r7NX-ptbk6xjKvv64dh-DOCUZnb0-FNEQNrGOYNw1oeoDSzmw0ZLIgRsMIEyyRfq-RbcL0c6hXdrvgo'),
('Excaliber', 'Fires a burst of three piercing sword projectiles. Reloading swings the sword, destroying nearby bullets and damaging nearby enemies. Increases curse by 2.5.', 'Once and Future', 'B', 'Burst', 'FULLAUTO', 'https://lh3.googleusercontent.com/hhLlEK64yh7Dfz1JEZCexJk__Qca9MTs8lmlmW9yMWiPGFzy-G-5ujSVPNFQYo_v_-iJNNQgW6IBbCd--GQsIyb2if9SVhvwWlJOO393'),
('Mahoguny', 'Fires bouncing explosive wood bullets and several leaves.', '100% Organic', 'C', 'Semiautomatic', 'EXPLOSIVE', 'https://lh3.googleusercontent.com/lSDAyxTpjyIxpG0k8ini2lpKktpVgM4kNmAhTl9qRJqnIfRh7gElP9f1PYaVqlZN6JkMFhlMg5MMpeIS5P54vE4Vc4EZtmXo7fAkpQ6MgA'),
('Megahand', 'Has 2 levels of damage depending on how long the gun has been charged.', '-P-', 'B', 'Charged', 'CHARGE', 'https://lh3.googleusercontent.com/MMuz_ACmbwUdEA3OjdfdZdR75cwM-7qWu_mqGbKTQe1Im0Md_ksE4iws_FVjKxjP0U9Nfs0_PtLEpjPCBqyyxgE9b1fxu52L8SFUsS-i'),
('3rd Party Controller', 'Upon hitting an enemy, they will move in the same direction the player moves, and shoot towards the crosshair if the player shoots.', 'Assuming Direct Control', 'A', 'Semiautomatic', 'CHARM', 'https://lh3.googleusercontent.com/di5_8b3TZ_7eYsC7SGpfKQhD9_f0hRJK3_oWXUWhXs_haWebJsypAhJ4IE-keRq7wDDV6SW0Y2Uzmm7cifeuUVfu7iB5OM0kofLlrdS8'),
('Demon Head', 'Fires a continuous beam that has a chance to inflict Burn and slightly homes in on enemies.', 'Wanged', 'B', 'Beam', 'BEAM', 'https://lh3.googleusercontent.com/uC3bJwX-ltz1qbE6gAxfP-QrhFaDgKHt3MK9Z_fY6_M2Qx40pCoxYAAQzOYxzsJOSKFx0NVggVxW77v9RWSkwY5efEDbAgPjLU2pilC7'),
('Gungeon Ant', 'In oil mode, creates oil puddles on impact. In fire mode, fires fireballs that pierce and burn. Reloading switches modes.', 'What Army?', 'C', 'Semiautomatic', 'FIRE', 'https://lh3.googleusercontent.com/8Oga3i2qYYQIli52JuAHBSfeZxsduoF5W3ox4TpjUtWw7ZkPsFjOdFoHJ6ATCUlX74DnkwioUbzVeGNtI9pLJxzFiG27XC_e-UBGmLRu'),
('Colt 45', 'Fires bullets that freeze enemies.', 'Shatterday Night Special', 'B', 'Semiautomatic', 'ICE', 'https://lh3.googleusercontent.com/G0RYGZdPbUHgbL35m5dRJlUFfCWJEZ61q1zpd3VC9PxhjhvsDR6ExM1ZaDm9wQRDQPtccLMwl5s_IlQ3N8j9VeAPTRtNKKwDn091M8coVQ'),
('Plunger', 'Fires a stream of poison. Has a chance to poison enemies and leaves poison puddles on impact.', 'Take Your Best Shot!', 'C', 'Beam', 'POISON', 'https://lh3.googleusercontent.com/HxxDCr7U_ob0qR_viptuwJrUp0gXgHc0Wt-Ucnl2xp0R8kUNE24NvWzsLf1gYjzQMr1wgtb_LnxNqogQILxj0A1fbGl-BrPsez7U4QCQCQ'),
('Kruller Glaive', 'Throws a boomerang-like projectile that homes in on multiple enemies, damaging and sometimes stunning them.', 'Studied the Blade', 'B', 'Charged', 'NONE', 'https://lh3.googleusercontent.com/g2WKyER1W_6ID8c5QvdytUJA4tYHAyro404lyL01l5ozMKLi5lmiLIcbyECHo55jKYDhT9yd75zg3NCUywji5ZRKpWHWpu3IOPxzo-gCoQ'),
